#!/bin/sh
#
# @name SDU Drone
#
# @type Hexarotor x
#

sh /etc/init.d/rc.mc_defaults

set MAV_TYPE 13
set MIXER hexa_x_sdu

param set NAV_DLL_ACT 0
param set NAV_RCL_ACT 0
param set COM_OBL_ACT 0
param set EKF2_AID_MASK 1
param set EKF2_HGT_MODE 0
param set SIM_GPS_BLOCK 0
param set PWM_AUX_MAX 2000
#param set EKF2_EV_DELAY 50.0
